service:
  stages:
    Build:
      runFirst:
        command: "wget https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip && mkdir tfcli && unzip terraform_1.8.5_linux_amd64.zip -d tfcli/terraform && chmod +x tfcli/terraform && rm terraform_1.8.5_linux_amd64.zip && tfcli/terraform -help"
#      runLast:
#        command: "tfcli/terraform -version"