service:
  stages:
    Build:
      runFirst:
        command: "wget https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip && mkdir tfcli && unzip terraform_1.8.5_linux_amd64.zip -d tfcli/terraform && chmod a+x tfcli/terraform && rm terraform_1.8.5_linux_amd64.zip && tfcli/terraform -version"
      runLast:
        command: "tfcli/terraform -version"