service:
  stages:
    Build:
      runFirst:
        command: "wget https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip && sudo unzip terraform_1.8.5_linux_amd64.zip -d /usr/local/bin"
      runLast:
        command: "terraform -version"  